name: SampleApp
options:
  bundleIdPrefix: com.mineoengine
settings: 
  base:
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
    DEVELOPMENT_TEAM: 8KMDCBT7AD
targets:
  SampleApp:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources: ["SampleApp"]
    info:
      path: SampleApp/Info.plist
